# Generated by Django 5.2.1 on 2025-05-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='capacidad_comensales',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='ciudad_estado',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='codigo_interno',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='entrega_domicilio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='horario',
            field=models.CharField(default='9:00-18:00', max_length=255),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='meta_diaria',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='numero_mesas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='zona_horaria',
            field=models.CharField(default='America/Mexico_City', max_length=50),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='telefono',
            field=models.CharField(max_length=100),
        ),
    ]
