# Generated by Django 5.2.1 on 2025-05-19 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sucursal_locacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=20)),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('esta_abierto', models.BooleanField(default=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='accounts.sucursal')),
            ],
            options={
                'unique_together': {('sucursal', 'dia')},
            },
        ),
    ]
