# Generated by Django 5.2.1 on 2025-05-19 21:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_sucursal_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariosucursal',
            options={'ordering': ['dia']},
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='meta_diaria',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
