# Generated by Django 5.2.1 on 2025-05-20 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_horariosucursal_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('user_created', 'Usuario Creado'), ('user_updated', 'Usuario Actualizado'), ('user_deleted', 'Usuario Eliminado'), ('sucursal_created', 'Sucursal Creada'), ('sucursal_updated', 'Sucursal Actualizada'), ('sucursal_deleted', 'Sucursal Eliminada'), ('login', 'Inicio de Sesión'), ('system', 'Sistema')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
