# Generated by Django 5.2.1 on 2025-05-20 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('Panadería', 'Panadería'), ('Lácteos', 'Lácteos'), ('Endulzantes', 'Endulzantes'), ('Condimentos', 'Condimentos'), ('Aceites', 'Aceites')], max_length=50)),
                ('tipo', models.CharField(choices=[('Materia Prima', 'Materia Prima'), ('Producto Terminado', 'Producto Terminado'), ('Insumo', 'Insumo')], max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('minimo', models.IntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='accounts.sucursal')),
            ],
            options={
                'db_table': 'insumos',
                'ordering': ['nombre'],
            },
        ),
    ]
