# Generated by Django 5.2.1 on 2025-05-21 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_categoria_alter_insumo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_interno', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad_estado', models.CharField(default='', max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='sucursal',
        ),
        migrations.CreateModel(
            name='InsumoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_unitario', models.DecimalField(decimal_places=2, help_text='Costo unitario del insumo con este proveedor', max_digits=10)),
                ('es_proveedor_principal', models.BooleanField(default=False, help_text='Indica si este es el proveedor principal para este insumo')),
                ('ultima_compra', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.insumo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.proveedor')),
            ],
            options={
                'verbose_name': 'Relación Insumo-Proveedor',
                'verbose_name_plural': 'Relaciones Insumo-Proveedor',
                'db_table': 'insumos_proveedores',
                'unique_together': {('insumo', 'proveedor')},
            },
        ),
        migrations.AddField(
            model_name='insumo',
            name='proveedores',
            field=models.ManyToManyField(blank=True, related_name='insumos', through='accounts.InsumoProveedor', to='accounts.proveedor'),
        ),
    ]
