# Generated by Django 5.2.1 on 2025-05-21 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_proveedor_fields'),
        ('accounts', '0011_proveedor_remove_insumo_costo_remove_insumo_sucursal_and_more'),
    ]

    operations = [
    ]
