# Generated by Django 5.2.1 on 2025-05-23 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_proveedor_codigo_interno'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoCompuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('unidad', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'insumos_compuestos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteInsumoCompuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_compuestos', to='accounts.insumo')),
                ('insumo_compuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='accounts.insumocompuesto')),
            ],
            options={
                'db_table': 'componentes_insumo_compuesto',
            },
        ),
    ]
