# Generated by Django 5.2.1 on 2025-05-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_movimientoinventario_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sucursales',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='accounts.sucursal', verbose_name='Sucursales asignadas'),
        ),
    ]
