# Generated by Django 5.2.1 on 2025-05-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumocompuesto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
