# Generated by Django 5.2.1 on 2025-05-29 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_insumoelaborado_ingredienteinsumoelaborado'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoElaboradoReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insumo_elaborado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_en_recetas', to='accounts.insumoelaborado')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos_elaborados', to='accounts.receta')),
            ],
            options={
                'db_table': 'insumos_elaborados_receta',
                'unique_together': {('receta', 'insumo_elaborado')},
            },
        ),
    ]
