# Generated by Django 5.2.1 on 2025-05-30 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_insumoelaboradoreceta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='porciones',
            field=models.IntegerField(default=1, help_text='Número de porciones'),
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.IntegerField(default=0, help_text='Tiempo en minutos'),
        ),
    ]
