# Generated by Django 5.2.1 on 2025-05-31 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_ingredienteinsumoelaborado_ingrediente_elaborado_solo_un_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20)),
                ('tipo_insumo', models.CharField(choices=[('compuesto', 'Insumo Compuesto'), ('elaborado', 'Insumo Elaborado')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(choices=[('produccion', 'Producción'), ('ajuste_inventario', 'Ajuste de inventario'), ('traspaso', 'Traspaso entre sucursales'), ('caducidad', 'Caducidad'), ('consumo_interno', 'Consumo interno'), ('venta', 'Venta'), ('merma', 'Merma'), ('otro', 'Otro')], max_length=100)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('insumo_compuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='accounts.insumocompuesto')),
                ('insumo_elaborado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='accounts.insumoelaborado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sucursal')),
                ('sucursal_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traspasos_insumos_destino', to='accounts.sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('insumo_compuesto__isnull', False), ('insumo_elaborado__isnull', True), ('tipo_insumo', 'compuesto')), models.Q(('insumo_compuesto__isnull', True), ('insumo_elaborado__isnull', False), ('tipo_insumo', 'elaborado')), _connector='OR'), name='movimiento_solo_un_tipo_insumo')],
            },
        ),
    ]
